---
- src: https://github.com/RedHatNordicsSA/ansible-role-resolv-conf.git
  scm: git
- src: https://github.com/RedHatNordicsSA/ansible-role-date-time.git
  scm: git
- src: https://github.com/RedHatNordicsSA/ansible-role-phpipam-get-ip.git
  scm: git
- src: https://github.com/RedHatNordicsSA/ansible-role-rhv-vm.git
  scm: git
- src: https://github.com/RedHatNordicsSA/ansible-role-satellite-bootstrap.git
  scm: git
- src: https://github.com/RedHatNordicsSA/ansible-role-ipa-client.git
  scm: git
- src: https://github.com/RedHatNordicsSA/ansible-role-nagios-nrpe.git
  scm: git
- src: https://github.com/RedHatNordicsSA/ansible-role-nagios-bootstrap.git
  scm: git
# - src: https://github.com/RedHatNordicsSA/ansible-role-ovirt-guest.git
#   scm: git
# - src: https://github.com/RedHatNordicsSA/ansible-role-dist-pub-key
#   scm: git
- RedHatInsights.insights-client
- geerlingguy.git
- geerlingguy.apache
- geerlingguy.php
- geerlingguy.mysql
- marcelnijenhof.firewalld
- name: gluster.infra
  scm: git
  src: https://github.com/gluster/gluster-ansible-infra
- name: gluster.cluster
  scm: git
  src: https://github.com/gluster/gluster-ansible-cluster
- name: zaxos.tomcat-ansible-role
